extends SceneTree

const Introspection = preload("res://addons/godot_control_mcp/commands/introspection.gd")
const Router = preload("res://addons/godot_control_mcp/command_router.gd")

func _init() -> void:
	var listed := Introspection.list_classes({"offset": 0, "limit": 10})
	assert(listed.ok)
	assert(listed.result.classes.size() == 10)
	assert(listed.result.total > listed.result.classes.size())
	var sorted_classes: Array = listed.result.classes.duplicate()
	sorted_classes.sort()
	assert(listed.result.classes == sorted_classes)
	assert(listed.result.hasMore)
	var bounded := Introspection.list_classes({"limit": 201})
	assert(not bounded.ok and "between 1 and 200" in bounded.hint)

	var node := Introspection.describe_class({"class": "Node"})
	assert(node.ok)
	assert(node.result.class == "Node")
	assert(node.result.inherits == "Object")
	assert(node.result.includeInherited == false)
	assert(node.result.methods.any(func(method): return method.name == "add_child" and method.args.size() >= 1 and method.has("return") and method.has("static") and method.has("vararg")))
	assert(node.result.methods.all(func(method): return method.owner == "Node" and method.declaredHere == true and method.has("signature")))
	assert(node.result.properties.any(func(property): return property.name == "process_mode" and property.has("type") and property.has("usage")))
	assert(node.result.signals.any(func(signal_info): return signal_info.name == "ready"))
	assert(node.result.has("enums") and node.result.has("constants"))
	assert(JSON.stringify(node.result).to_utf8_buffer().size() < 262144)
	var paged := Introspection.describe_class({"class": "Node", "memberOffset": 0, "memberLimit": 20})
	assert(paged.ok and paged.result.memberPage.limit == 20 and paged.result.memberPage.total > 20 and paged.result.memberPage.hasMore)
	var page_member_count: int = paged.result.methods.size() + paged.result.properties.size() + paged.result.signals.size() + paged.result.enums.size() + paged.result.constants.size()
	assert(page_member_count <= 20)
	assert(JSON.stringify(paged.result).to_utf8_buffer().size() < 262144)
	assert(not Introspection.describe_class({"class": "Node", "memberLimit": 501}).ok)
	var unknown := Introspection.describe_class({"class": "DefinitelyNotAGodotClass"})
	assert(not unknown.ok and "known ClassDB class" in unknown.hint)

	var mesh := Introspection.search({"query": "mesh", "offset": 0, "limit": 25})
	assert(mesh.ok and mesh.result.results.size() > 0)
	var sorted_results: Array = mesh.result.results.duplicate()
	sorted_results.sort_custom(Introspection.compare_search_results)
	assert(mesh.result.results == sorted_results)
	assert(mesh.result.results.any(func(result): return "mesh" in (result.class + " " + result.get("member", "")).to_lower()))
	assert(JSON.stringify(mesh.result).to_utf8_buffer().size() < 262144)
	assert(not Introspection.search({"query": "", "limit": 10}).ok)
	assert(not Introspection.search({"query": "mesh", "limit": 101}).ok)

	var router := Router.new()
	assert(router.register_command("introspection.list_classes", Introspection.list_classes))
	assert(router.register_command("introspection.describe_class", Introspection.describe_class))
	assert(router.register_command("introspection.search", Introspection.search))
	var response := router.dispatch({"jsonrpc": "2.0", "id": 1, "method": "introspection.list_classes", "params": {"limit": 3}})
	assert(response.result.classes.size() == 3)
	assert(JSON.stringify(response).to_utf8_buffer().size() < 262144)
	print("PASS live ClassDB introspection")
	quit()
