extends SceneTree

const Edit = preload("res://addons/godot_control_mcp/commands/edit.gd")
const Compat = preload("res://addons/godot_control_mcp/godot_compat.gd")
var failures: Array[String] = []

func _initialize() -> void: call_deferred("_run")
func _check(value: bool, message: String) -> void:
	if not value: failures.append(message); push_error(message)

func _run() -> void:
	EditorInterface.open_scene_from_path("res://phase3/node_fixture.tscn")
	for ignored in range(30): await process_frame
	var root := EditorInterface.get_edited_scene_root()
	_check(root != null, "fixture must open")
	var undo: EditorUndoRedoManager = Compat.editor_undo_redo()
	var root_version := Compat.undo_history_version(undo, root)
	var bad_add: Dictionary = Edit.node_add({"parent": "/root/Main", "type": "Node2D", "name": "Bad", "properties": {"position": 42}})
	_check(not bad_add.ok and root.get_node_or_null("Bad") == null, "invalid primitive initial property rejected")
	_check(Compat.undo_history_version(undo, root) == root_version, "invalid add leaves history unchanged")
	var traversal: Dictionary = Edit.node_get({"path": "/root/Main/B/../A"})
	_check(not traversal.ok, "noncanonical traversal path rejected")
	var added: Dictionary = Edit.node_add({"parent": "/root/Main", "type": "Node2D", "name": "Added", "properties": {"position": "Vector2(10,20)"}})
	_check(added.ok and root.get_node_or_null("Added") != null, "add with initial property")
	_check(Compat.undo_history_version(undo, root) == root_version + 1, "add increments history exactly once")
	var controller = preload("res://addons/godot_control_mcp/edit_controller.gd").new(undo)
	controller._last_history_target = root
	controller.undo(); _check(root.get_node_or_null("Added") == null, "undo add")
	controller.redo()
	var redone_added: Node2D = root.get_node("Added")
	_check(redone_added.position == Vector2(10, 20) and redone_added.owner == root, "redo add restores initial property and owner")
	var added_node := root.get_node("Added")
	var rename_version := Compat.undo_history_version(undo, added_node)
	var renamed: Dictionary = Edit.node_rename({"path": "/root/Main/Added", "name": "Renamed"})
	_check(renamed.ok and root.get_node_or_null("Renamed") != null, "rename changes path")
	_check(Compat.undo_history_version(undo, added_node) == rename_version + 1, "rename increments history once")
	Compat.undo_history_undo(undo, added_node); _check(added_node.name == "Added", "undo rename restores name")
	Compat.undo_history_redo(undo, added_node); _check(added_node.name == "Renamed", "redo rename")
	var property_version := Compat.undo_history_version(undo, added_node)
	var set_result: Dictionary = Edit.node_set_property({"path": "/root/Main/Renamed", "property": "position", "value": {"$type": "Vector2", "x": 7, "y": 8}})
	_check(set_result.ok and root.get_node("Renamed").position == Vector2(7, 8), "set property Variant")
	_check(Compat.undo_history_version(undo, added_node) == property_version + 1, "property increments history once")
	Compat.undo_history_undo(undo, added_node); _check(added_node.position == Vector2(10, 20), "undo property exact restoration")
	Compat.undo_history_redo(undo, added_node); _check(added_node.position == Vector2(7, 8), "redo property")
	var invalid_property_version := Compat.undo_history_version(undo, added_node)
	var bad_primitive: Dictionary = Edit.node_set_property({"path": "/root/Main/Renamed", "property": "position", "value": 9})
	var bad_object: Dictionary = Edit.node_set_property({"path": "/root/Main/Renamed", "property": "owner", "value": 9})
	_check(not bad_primitive.ok and not bad_object.ok and added_node.position == Vector2(7, 8), "primitive and object/class mismatches rejected")
	_check(Compat.undo_history_version(undo, added_node) == invalid_property_version, "invalid properties leave history unchanged")
	var source_child := Node2D.new(); source_child.name = "SourceChild"; source_child.position = Vector2(41, 42); added_node.add_child(source_child)
	added_node.owner = null; source_child.owner = null
	root_version = Compat.undo_history_version(undo, root)
	var duplicated: Dictionary = Edit.node_duplicate({"path": "/root/Main/Renamed", "parent": "/root/Main", "name": "Copy", "flags": 15})
	_check(duplicated.ok and root.get_node_or_null("Copy") != null, "duplicate")
	var copy: Node2D = root.get_node("Copy")
	var copied_child: Node2D = copy.get_node("SourceChild")
	_check(copy.position == added_node.position and copied_child.position == source_child.position and copy != added_node and copied_child != source_child, "duplicate subtree is isolated with copied state")
	_check(copy.owner == root and copied_child.owner == root, "duplicate assigns edited root recursively for ownerless source")
	_check(Compat.undo_history_version(undo, root) == root_version + 1, "duplicate increments history once")
	Compat.undo_history_undo(undo, root); _check(copy.get_parent() == null, "undo duplicate removes only copy")
	Compat.undo_history_redo(undo, root); _check(copy.get_parent() == root and copy.owner == root and copied_child.owner == root, "redo duplicate restores recursive persistence owner")
	var old_global: Transform2D = copy.global_transform
	var old_index := copy.get_index()
	var old_owner: Node = copy.owner
	var reparent_version := Compat.undo_history_version(undo, copy)
	var reparented: Dictionary = Edit.node_reparent({"path": "/root/Main/Copy", "parent": "/root/Main/B"})
	_check(reparented.ok and root.get_node_or_null("B/Copy") != null, "reparent")
	_check(Compat.undo_history_version(undo, copy) == reparent_version + 1, "reparent increments history once")
	Compat.undo_history_undo(undo, copy)
	_check(copy.get_parent() == root and copy.get_index() == old_index and copy.owner == old_owner and copy.global_transform == old_global, "undo reparent restores parent/index/owner/transform")
	Compat.undo_history_redo(undo, copy); _check(copy.get_parent() == root.get_node("B"), "redo reparent")
	var parent_b := root.get_node("B")
	var before_sibling := Node.new(); before_sibling.name = "Before"; parent_b.add_child(before_sibling); before_sibling.owner = root
	var after_sibling := Node.new(); after_sibling.name = "After"; parent_b.add_child(after_sibling); after_sibling.owner = root
	parent_b.move_child(copy, 1)
	var child := Node2D.new(); child.name = "Child"; child.position = Vector2(21, 22); copy.add_child(child); child.owner = root
	var grandchild := Node2D.new(); grandchild.name = "Grandchild"; grandchild.position = Vector2(31, 32); child.add_child(grandchild); grandchild.owner = root
	var delete_index := copy.get_index()
	var delete_version := Compat.undo_history_version(undo, parent_b)
	var deleted: Dictionary = Edit.node_delete({"path": "/root/Main/B/Copy"})
	_check(deleted.ok and root.get_node_or_null("B/Copy") == null, "delete")
	_check(Compat.undo_history_version(undo, parent_b) == delete_version + 1, "delete increments history once")
	Compat.undo_history_undo(undo, parent_b)
	_check(parent_b.get_node_or_null("Copy") == copy and copy.get_index() == delete_index, "undo delete restores original sibling index")
	_check(copy.get_node_or_null("Child/Grandchild") == grandchild and child.position == Vector2(21, 22) and grandchild.position == Vector2(31, 32), "undo delete restores full hierarchy and stored values")
	_check(copy.owner == old_owner and child.owner == root and grandchild.owner == root, "undo delete restores explicit recursive owners")
	Compat.undo_history_redo(undo, parent_b); _check(copy.get_parent() == null and child.get_parent() == copy and grandchild.get_parent() == child, "redo delete removes whole retained subtree")
	var stale: Dictionary = Edit.node_get({"path": "/root/Main/Missing"})
	_check(not stale.ok and "Current tree" in stale.hint and "/root/Main/A" in stale.hint and stale.hint.length() <= 2048, "stale path bounded hierarchical tree")
	var proto: Dictionary = Edit.node_set_property({"path": "/root/Main", "property": "__proto__", "value": 1})
	_check(not proto.ok, "prototype-like properties rejected")
	print("PASS phase 3 undoable node tools")
	quit(0 if failures.is_empty() else 1)
